Replace all kinds of buttons to ue-button.
universal-editor/universal-editor pull request #103
Opened 2017-01-31 15:31 UTC by AlekseySorokin

Issue: https://github.com/universal-editor/universal-editor/issues/99

2017-02-01 08:23 UTC, muravev approved these changes

2017-02-01 09:36 UTC, niksamokhvalov requested changes

2017-02-01 09:36 UTC, niksamokhvalov commented on src/demoApp/components.controller.js
>                                                      label: 'Send request to server',
Текст на кнопке и её реальное действие не соответствуют друг другу.

2017-02-01 09:36 UTC, niksamokhvalov commented on src/module/components/ueButton/ueButton.controller.js
> +                    if (confirm('Удалить запись «' + vm.entityId + '»?')) {
@AlekseySorokin все сообщения пишутся через функционал локализации!

2017-02-01 09:36 UTC, niksamokhvalov commented on src/module/components/ueFilter/ueFilter.controller.js
>                  settings.footer = {
А почему тут? По-моему, кнопки надо вставлять во вьюхе.

2017-02-01 09:36 UTC, niksamokhvalov commented on webpack.config.js
> +    //  console.log(RUNNING_SERVER);
Зачем эта строчка нужна?

2017-02-02 12:18 UTC, AlekseySorokin commented on src/module/components/ueFilter/ueFilter.controller.js
>                  settings.footer = {
зачем нам фильтр без кнопок, запускающие фильтр? Если toolbar не задан. Пусть выводятся по умолчанию. Если все же кнопки не нужны, то пусть пишут toolbar:[].

2017-02-02 12:29 UTC, AlekseySorokin commented on src/module/components/ueButton/ueButton.controller.js
> +                    if (confirm('Удалить запись «' + vm.entityId + '»?')) {
да. поправлю.

2017-02-02 12:37 UTC, AlekseySorokin commented on src/module/components/ueButton/ueButton.controller.js
> +                    if (confirm('Удалить запись «' + vm.entityId + '»?')) {
поправил.

2017-02-02 12:39 UTC, AlekseySorokin commented on src/demoApp/components.controller.js
>                                                      label: 'Send request to server',
почему же?
Отправка запроса с предобработчиком по указанному адресу.

2017-02-02 12:39 UTC, AlekseySorokin commented on webpack.config.js
> +    //  console.log(RUNNING_SERVER);
Исключил из кода.

2017-02-02 13:05 UTC, niksamokhvalov approved these changes

2017-02-02 13:06 UTC, merged