Work api
universal-editor/universal-editor pull request #107
Opened 2017-02-10 13:34 UTC by muravev

Добавлена функциональность работы редактору с методами getMethod, getURL, getHeader, getParams, getData, processResponse стороннего сервиса при создание/обновление/удаление/получение записи и при запросе на получение списка записей.

2017-03-14 11:17 UTC, niksamokhvalov commented on dist/articlesGrid.controller.js
> +            type: 'articles',
А на что влияет это поле?

2017-03-14 11:17 UTC, niksamokhvalov commented on dist/index.js
> +    angular.module('demoApp', ['ui.router', 'universal-editor', 'JSONAPIService']);
JSONAPIService — это же не наше, да? :)

2017-03-14 12:08 UTC, AlekseySorokin commented on dist/articlesGrid.controller.js
> +            type: 'articles',
Как ты помнишь это требует спецификация. Параметр type всегда приходит в api. Игорь как-то говорил уже об этом. Я подтверждаю.

2017-03-14 12:10 UTC, AlekseySorokin commented on dist/index.js
> +    angular.module('demoApp', ['ui.router', 'universal-editor', 'JSONAPIService']);
Это это вот как раз сервис, который формирует и парсит JSONAPI запросы и ответы.

2017-03-14 12:12 UTC, AlekseySorokin commented on dist/index.js
> +    angular.module('demoApp', ['ui.router', 'universal-editor', 'JSONAPIService']);
Или его прям ядре подключать лучше?

2017-03-14 12:23 UTC, AlekseySorokin commented on dist/articlesGrid.controller.js
> +            type: 'articles',
На одном из миттингов было решено прописывать его в соурсах, если используется этот тип взаимодействия с АПИ.

2017-03-14 13:36 UTC, AlekseySorokin commented on dist/index.js
> +    angular.module('demoApp', ['ui.router', 'universal-editor', 'JSONAPIService']);
Да этот вопрос обговаривался. Я его включил в сборку редактора, поэтому подключать его вручную не придется.

2017-03-19 07:56 UTC, niksamokhvalov requested changes

2017-03-19 07:56 UTC, niksamokhvalov commented on dist/articlesGrid.controller.js
> +            type: 'articles',
Хорошо, но тогда уж `resourceType`, что бы было понятнее (в терминах JSONAPI).

2017-03-19 07:56 UTC, niksamokhvalov commented on dist/articlesGrid.controller.js
> +                            label: 'Статус',
Можем лейблы тоже на английском делать?

2017-03-19 08:17 UTC, AlekseySorokin commented on dist/articlesGrid.controller.js
> +            type: 'articles',
+

2017-03-19 08:17 UTC, AlekseySorokin commented on dist/articlesGrid.controller.js
> +                            label: 'Статус',
+

2017-03-19 08:27 UTC, niksamokhvalov approved these changes

2017-03-19 08:28 UTC, merged