Вывод сообщений в случае ошибок с подгрузкой данных и поведение readonly компонент при отсутствии значений.
universal-editor/universal-editor pull request #111
Opened 2017-02-21 12:44 UTC by AlekseySorokin

При неудачном запросе вместо компонента выводятся сообщения с текстом ошибок. (ошибки извлекаются из ответа от сервера или выводятся по-умолчанию в зависимости от статуса).
В режиме создания новой записи:
1. Пустые компоненты readonly не отображаются в режиме создания новой записи.
2. Пустые табы и  табы имеющие в своем составе только пустые readonly компоненты.

2017-02-21 12:47 UTC, AlekseySorokin commented
close:[Issue](https://github.com/universal-editor/universal-editor/issues/106)

2017-02-21 13:47 UTC, niksamokhvalov requested changes
Развернул локально, не работает: http://take.ms/IyiUV. ХТТП-статус 404. Грид как рисовался, так и рисуется без каких-либо уведомлений.

2017-02-21 13:47 UTC, niksamokhvalov commented on src/module/localization.configFile.js
> +                'N502': 'Сервис вернул неожиданный ответ.',
Опечатка: не сервис, а сервер.

2017-02-21 13:47 UTC, niksamokhvalov commented on src/module/localization.configFile.js
> +                'N400': 'Неправильно заполнена форма.',
N400, N401 и т. д. — что это за коды? Расскажи, пожалуйста.

2017-02-27 17:02 UTC, niksamokhvalov approved these changes

2017-02-27 17:02 UTC, merged