Description of parameters `useable` и `readonly`.
universal-editor/universal-editor pull request #136
Opened 2017-04-10 11:23 UTC by AlekseySorokin

Описание параметров `useable` и `readonly`.

2017-04-10 13:06 UTC, niksamokhvalov requested changes

2017-04-10 13:06 UTC, niksamokhvalov commented on docs/ru/components/useable.md
> +# Условное отображение и условное редактирование компонента
Лёш, ты взялся за хорошее дело — описать способы настройки отображения компонентов. Но эта статья не будет завершённой без описания `disabled`. Давай добавим?

2017-04-10 13:06 UTC, niksamokhvalov commented on docs/ru/components/useable.md
> +              visibility: function(data) {
Ошибка, нет такой настройки.

2017-04-10 13:35 UTC, AlekseySorokin commented on docs/ru/components/useable.md
> +              visibility: function(data) {
блин) точняк.

2017-04-10 14:14 UTC, NobodyDies commented
вроде все нормально. Есть пара вопросов - в функцию в качестве аргумента передаются значения всех компонентов? То есть, будет ли возможность ориентироваться на те значения которые не отображаются в редакторе - допустим модель в в компоненте ui-select помимо name и id которые участвуют в формировании компонента у каждого элемента будет type, по которому и нужно проверять отображать ли тот или иной кусок админки?

2017-04-10 14:30 UTC, AlekseySorokin commented
Ок, я учту. Данные в аргументе буду возвращать в развернутом виде как приходит в API.

2017-04-18 16:45 UTC, niksamokhvalov requested changes

2017-04-18 16:45 UTC, niksamokhvalov commented on src/module/services/EditEntityStorage.service.js
> +            $rootScope.$broadcast('ue:componentValueChanged', output);
Алексей, задокументировать новое событие не желаешь?

2017-04-18 16:45 UTC, niksamokhvalov commented on docs/ru/components/README.md
> +* [Cпособы настройки отображения компонентов](visualization.md)
Переименуй в «Управление отображением», пожалуйста.

2017-04-18 16:45 UTC, niksamokhvalov commented on docs/ru/components/main.md
> +| settings[readonly] | bool или function | Параметр отвечает за указание активности компонента с точки зрения взаимодействия с пользователем  (см. [подробнее](visualization.md). | - | false |
Во-первых слетело оформление в «см. подробнее». Во-вторых, что значит «см. подробнее»?)) Переформулируй, напиши аккуратнее, пожалуйста. И последующие пункты с ошибками написаны.

2017-04-18 16:45 UTC, niksamokhvalov commented on src/module/controllers/Base.controller.js
> +                    $scope.$broadcast('ue-group:forceUseable', {
А мы не хотим задокументировать это событие?

2017-04-21 12:49 UTC, niksamokhvalov requested changes

2017-04-21 12:49 UTC, niksamokhvalov commented on docs/ru/events.md
> +Событие вызывается при принудительной установке значений параметров `useable` и `readonly` у компонентов внутри контейнера `ue-group`.
Опиши поподробнее: как это может использоваться? что означает «принудительная установка значения»?

2017-04-21 12:49 UTC, niksamokhvalov commented on docs/ru/events.md
> +### ue:componentValueChanged
Если событие относится к компоненту ue-form, почему событие называется ue:?

2017-04-21 15:07 UTC, niksamokhvalov approved these changes

2017-05-06 14:56 UTC, merged