Drag and drop documentation.
universal-editor/universal-editor pull request #139
Opened 2017-04-13 03:47 UTC by AlekseySorokin

Documentation for d&d in ue-grid component.

2017-04-13 08:19 UTC, NobodyDies commented
было бы неплохо в функцию `dragDisable` передавать еще и `destElement`

2017-04-13 10:26 UTC, AlekseySorokin commented
`dragDisable` совсем отключает перенос для элемента. Если он вернет для dragElement false, то его мышкой взять нельзя будет.

2017-04-13 10:35 UTC, AlekseySorokin commented
Для такой динамики тогда все лучше сделать коллбеками. И сам тип записи в том числе.

2017-04-13 13:30 UTC, AlekseySorokin commented
Но для allowedTypes и type оставил возможность прописать константное значение.

2017-04-13 13:36 UTC, NobodyDies commented
в случае callback насколько я понимаю пользователь будет видеть что элемент встает на нужное место пока не отпустит левую кнопку мышки, тогда сюрприз и случится. 
`type` и `allowedTypes` получается будет просчитываться динамично на момент перетаскивания элемента, `type` для самого элемента, а `allowedTypes` - для `destElement`?

2017-04-14 05:33 UTC, AlekseySorokin commented
Да будет динамично заполняться..

2017-04-24 13:38 UTC, NobodyDies commented
не всегда получается засунуть 1 элемент в другой, и не всегда получается вытащить элемент выше по уровню вложенности

2017-04-25 11:55 UTC, niksamokhvalov requested changes

2017-04-25 11:55 UTC, niksamokhvalov commented on demo/newsGrid.controller.js
> +                        type: function(element, collection) {
Давай научимся принимать как колбэк, так и строку. Здесь явно избыточен колбэк, можно просто строку `'news'` передать.

2017-04-25 11:55 UTC, niksamokhvalov commented on demo/newsGrid.controller.js
> +                    dragMode: {
Предлагаю убрать параметры, которое не используются, что бы они не сбивали с толку (displayHeaderColumns, start, over и т. д.).

2017-04-25 11:55 UTC, niksamokhvalov commented on docs/ru/components/dragMode.md
> +* `dragIcon` – флаг наличия иконки для перетаскивания. Иконка расположена в конце. Перетаскивать узел можно только с помощью неё.
Что делать, если я захочу поместить иконку не в конце, а в начале? В середине?

2017-04-25 11:55 UTC, niksamokhvalov commented on demo/newsGridDnD.controller.js
> +                                            last: '>>',
У нас же есть значения по умолчанию, зачем тут лейблы?

2017-04-25 11:55 UTC, niksamokhvalov commented on docs/ru/components/dragMode.md
> +* `expandHandler` – функция возвращает Promise объект. Является обработчиком иконки для раскрытия узлов. Доступные аргументы `parentElement` – родительский объект, для которого подгружаются дочерние
По-моему слово Handler тут лишнее. Выше же параметры без handler-а названы: start, over, drop. Как думаешь?

2017-04-25 11:55 UTC, niksamokhvalov commented on docs/ru/components/dragMode.md
> +* `type` – функция возвращает строковое значение, и задает группу переносимых элементов. Допускается прописать обычное константное значение, если коллбек не нужен;
Мне кажется, type — эти очень отстранённое название, которое при любом поводе используется. Как на счёт `containerName`? По факту, мы перемещаем узлы из одного контейнера в другой. И, соответственно, вторая настройка — `allowedContainers`.

2017-04-25 11:55 UTC, niksamokhvalov commented on docs/ru/components/main.md
> +Получение модели компонента по его настройкам возможно с помощью метода `getComponentBySetting` сервиса `EditEntityStorage`.
Стоит написать, зачем это может понадобиться.

2017-04-25 11:55 UTC, niksamokhvalov commented on docs/ru/components/ue-grid.md
> +| settings[dataSource][tree][selfField] | string | Имя поля с объектом, к которому привязан узел.  | + | - |
Описание не понятное. И я сам, если честно, не очень понимаю, зачем это нужно?

2017-04-25 11:55 UTC, niksamokhvalov commented on docs/ru/components/ue-grid.md
> +| settings[columns] | array или string | Массив объектов для описания столбцов или имя поля из конфигурации ресурса.  | + | - |
> array или string

Следуя этому утверждению, в `columns` можно передать строку: `'columns': 'id',`. Это так?

2017-04-25 12:03 UTC, niksamokhvalov commented
@AlekseySorokin, есть предложение по стилизации курсора. Посмотри https://webref.ru/css/cursor. Предлагаю следующее. Когда наводим на `dragIcon`, делаем курсор `grab`. Когда потащили узел, делаем курсор `grabbing`.

2017-04-25 14:17 UTC, AlekseySorokin commented on docs/ru/components/dragMode.md
> +* `dragIcon` – флаг наличия иконки для перетаскивания. Иконка расположена в конце. Перетаскивать узел можно только с помощью неё.
Тут ничего не сделаешь, он всегда в конце будет.
Зачем нам иконка в середине?

2017-04-25 14:18 UTC, AlekseySorokin commented on docs/ru/components/dragMode.md
> +* `dragIcon` – флаг наличия иконки для перетаскивания. Иконка расположена в конце. Перетаскивать узел можно только с помощью неё.
И формулировка была 'Иконку справа, в конце строки, за которую можно перетащить узел'.
И сейчас в голову не приходит как это сделать динамично.

2017-04-25 14:48 UTC, AlekseySorokin commented on docs/ru/components/ue-grid.md
> +| settings[columns] | array или string | Массив объектов для описания столбцов или имя поля из конфигурации ресурса.  | + | - |
Да.

2017-04-26 14:17 UTC, AlekseySorokin commented
Добавил еще одну настройку. `mode`, которая принимает значения move и copy. Т. к. не всегда нужно удалять запись из контейнера при переносе.

2017-04-27 11:02 UTC, niksamokhvalov requested changes

2017-04-27 11:02 UTC, niksamokhvalov commented on docs/ru/components/dragMode.md
> +                    mode: 'copy' || 'move',
Давай реальный код писать. Это ж не будет работать.

2017-05-06 14:56 UTC, merged