Initial behavour for component ue-form.
universal-editor/universal-editor pull request #146
Opened 2017-04-19 11:59 UTC by AlekseySorokin

Enhancement for parameter `sref` of the ue-button +
new parameter `primaryKeyValue` for configuring of `ue-form`.
close #131

2017-04-21 12:57 UTC, niksamokhvalov approved these changes

2017-04-21 13:34 UTC, niksamokhvalov requested changes

2017-04-21 13:34 UTC, niksamokhvalov commented on demo/staffGrid.controller.js
> +                                        parameters: function(id, primaryKey, records) {
Давай абстрагируемся от грида. Пусть грид бросает событие с данными из «нажатой строки», а колбэк слушает его.

2017-04-25 12:24 UTC, niksamokhvalov requested changes
Не нашёл в документации описания события `ue-grid:сontextMenu`. Я плохо искал?

2017-04-25 12:24 UTC, niksamokhvalov commented on docs/ru/components/ue-form.md
> +| settings[primaryKeyValue] | function или string или number | Значение идентификатора записи, за которым будет отправляться запрос к API. | - | - |
Надо описать, что будет, если этот параметр не задавать вообще.

2017-04-25 12:24 UTC, niksamokhvalov commented on docs/ru/events.md
> ++ `records` – полный перечень записей;
Зачем нам все записи могут понадобиться? Почему одной недостаточно?

2017-04-25 12:24 UTC, niksamokhvalov commented on src/module/components/ueForm/ueForm.component.js
> +     * @example <ue-form></ue-for>
form, ue-form.

2017-04-26 06:24 UTC, AlekseySorokin commented on src/module/components/ueForm/ueForm.component.js
> +     * @example <ue-form></ue-for>
поправил.

2017-04-26 06:24 UTC, AlekseySorokin commented on docs/ru/events.md
> ++ `records` – полный перечень записей;
Да. Думаю достаточно одной. поправил.

2017-04-26 06:25 UTC, AlekseySorokin commented on docs/ru/components/ue-form.md
> +| settings[primaryKeyValue] | function или string или number | Значение идентификатора записи, за которым будет отправляться запрос к API. | - | - |
Отписал.

2017-05-06 15:30 UTC, niksamokhvalov approved these changes

2017-05-06 15:31 UTC, merged