D&d for the multiple ue-autocomplete.
universal-editor/universal-editor pull request #165
Opened 2017-05-16 08:17 UTC by AlekseySorokin

Компонент Автозаполнение (ue-autocomplete) в множественном режиме получил возможность перетаскивать установленные значения.

2017-05-16 12:07 UTC, niksamokhvalov requested changes
Зачем большой фиксированный контейнер-тень переносимому элементу?

https://monosnap.com/file/BsUMw3bXLijtZuNvAEUkVNPkJTDfgm

Контейнер-тень должен быть такого же размера, как реальный контейнер.

2017-06-15 12:41 UTC, niksamokhvalov requested changes
Отлично! Давай только сам контейнер (который начинаем перемещать) будем скрывать, оставляя на его месте только контейнер-тень — http://take.ms/Z5HoU. Ибо сейчас выглядит странно, как будто в глазах двоится :)

2017-07-05 09:02 UTC, AlekseySorokin commented
Сделано.

2017-07-06 12:48 UTC, niksamokhvalov commented
Готов мержить, но нам же надо и в разделе Components продемонстрировать эту возможность. Давай туда добавим, в блок с автокомплитами.

2017-07-07 07:46 UTC, AlekseySorokin commented
Добавил демо.

2017-07-07 14:15 UTC, merged