Sortable col ue grid
universal-editor/universal-editor pull request #169
Opened 2017-05-25 08:35 UTC by Sergey73

2017-05-27 11:30 UTC, niksamokhvalov approved these changes

2017-05-29 08:31 UTC, AlekseySorokin approved these changes

2017-06-15 12:52 UTC, niksamokhvalov requested changes

2017-06-15 12:52 UTC, niksamokhvalov commented on demo/DnD.controller.js
> +                        width: "200px",
Зачем тут двойные кавычки?

2017-06-15 12:52 UTC, niksamokhvalov commented on docs/ru/components/ue-grid.md
> +| settings[columns][sortable] | boolean | разрешает/запрещает сортировку данных по столбцу | - | true |
Предложение должно начинаться с большой буквы. До и после символа «/» должны быть пробелы. Не то что бы я придираюсь, просто давайте оформим документацию аккуратно.

2017-07-11 07:53 UTC, AlekseySorokin commented
Готово.

2017-07-11 13:51 UTC, niksamokhvalov approved these changes

2017-07-11 13:52 UTC, merged