Parameter whiteSpace in regim disabled.
universal-editor/universal-editor pull request #170
Opened 2017-05-25 16:27 UTC by AlekseySorokin

Добавлен параметр whiteSpace, который позволяет выводить компонент в режиме disabled и отображать его с учетом пробелов и переноса строк.

2017-05-27 11:28 UTC, niksamokhvalov requested changes

2017-05-27 11:28 UTC, niksamokhvalov commented on demo/components.controller.js
> +                                                    defaultValue: 'Строка с переносами. \n Перенос.',
Only english.

2017-05-27 11:28 UTC, niksamokhvalov commented on docs/ru/components/ue-textarea.md
> +| settings[whiteSpace] | boolean | Включает/выключает переносы строк и лишние пробелы при выводе текста в режиме disabled. | - | - |
Слушай, а ты уверен, что этот параметр вообще нужен? Как мне кажется, если поле задисейблено, то текст всегда должен показываться с переносами. Разве могут быть случаи, когда надо рендерить без них?

2017-05-29 07:12 UTC, AlekseySorokin commented on docs/ru/components/ue-textarea.md
> +| settings[whiteSpace] | boolean | Включает/выключает переносы строк и лишние пробелы при выводе текста в режиме disabled. | - | - |
В общем да. Пусть будет такое поведение всегда конкретно для ue-textarea.

2017-05-29 07:13 UTC, AlekseySorokin commented on demo/components.controller.js
> +                                                    defaultValue: 'Строка с переносами. \n Перенос.',
Поправил.

2017-07-04 13:16 UTC, niksamokhvalov approved these changes

2017-07-04 13:16 UTC, merged