Optimization.
universal-editor/universal-editor pull request #173
Opened 2017-06-07 07:46 UTC by AlekseySorokin

Проведена оптимизация компонентов в целях облегчения работы приложения.

2017-06-08 14:45 UTC, niksamokhvalov requested changes
Отлично, надо только в документации опечатки исправить.

2017-06-08 14:45 UTC, niksamokhvalov commented on docs/ru/components/ue-grid.md
> +* ue-grid:updateNodes – cобытие слушается компонентом в режиме `drag and drop`. Если отдать событию ссылку на какую-то из отрисованных записей, то он инициирует цепочку событий `ue:componentDataLoade
> то обновиться только эта запись

Опечатка: обнови**тся**.

2017-06-08 14:45 UTC, niksamokhvalov commented on docs/ru/components/ue-grid.md
> +* ue-grid:updateNodes – cобытие слушается компонентом в режиме `drag and drop`. Если отдать событию ссылку на какую-то из отрисованных записей, то он инициирует цепочку событий `ue:componentDataLoade
Тут не опечатка ли? Дважды описано событие `ue-grid:updateNodes`.

2017-06-08 14:45 UTC, niksamokhvalov commented on docs/ru/components/ue-grid.md
> +Обычный вызов события поведет обновление всех значений компонента.
«Поведет» — это как?

2017-06-08 14:45 UTC, niksamokhvalov commented on src/module/directives/renderTemplate.directive.js
> +            element.addClass('component-preview');
Классам надо делать приставку `ue`.

2017-06-09 16:00 UTC, AlekseySorokin commented on src/module/directives/renderTemplate.directive.js
> +            element.addClass('component-preview');
Это CSS классы. Тут чтобы не создавать лишних вотчеров класс вешается из кода.

2017-06-15 12:46 UTC, niksamokhvalov commented on src/module/directives/renderTemplate.directive.js
> +            element.addClass('component-preview');
Это понятно. Но ничто не мешает пользователю редактора создать ЦСС-класс с таким же названием, и тогда на этот элемент навесится его стиль.

2017-06-15 12:46 UTC, niksamokhvalov approved these changes

2017-06-15 12:47 UTC, merged