Updating datepicker library.
universal-editor/universal-editor pull request #179
Opened 2017-07-04 16:09 UTC by AlekseySorokin

Обновление компонента ue-date (bootstrap-datetimepicker)

2017-07-06 12:55 UTC, niksamokhvalov requested changes

2017-07-06 12:55 UTC, niksamokhvalov commented on demo/components.controller.js
> +                    code: 'ru'
Алексей, ты же знаешь, демка у нас только на английском.

2017-07-06 13:07 UTC, AlekseySorokin commented on demo/components.controller.js
> +                    code: 'ru'
Это чтобы ты видел откуда берется язык. =)

2017-07-06 13:16 UTC, AlekseySorokin commented on demo/components.controller.js
> +                    code: 'ru'
Убрал.

2017-07-07 14:17 UTC, niksamokhvalov commented on demo/components.controller.js
> +                    code: 'ru'
😃 👍

2017-07-07 14:34 UTC, niksamokhvalov approved these changes

2017-07-07 14:34 UTC, merged