Restyling dn d
universal-editor/universal-editor pull request #181
Opened 2017-07-10 10:13 UTC by Sergey73

2017-07-11 07:49 UTC, AlekseySorokin commented on src/module/components/ueGrid/ueNode/ueNode.controller.js
> +      function removeParentClass() {
Не найду где используется. Мне кажется это должен быть обработчик для 'dragleave'.

2017-07-11 08:43 UTC, AlekseySorokin approved these changes

2017-07-11 13:42 UTC, niksamokhvalov requested changes

2017-07-11 13:42 UTC, niksamokhvalov commented on docs/ru/components/dragMode.md
> +При перетаскивании, родительскому элементу будет присвоен класс `dnd-parent-node`.
Лишняя запятая.

2017-07-11 13:42 UTC, niksamokhvalov commented on docs/ru/components/dragMode.md
> +При перетаскивании, родительскому элементу будет присвоен класс `dnd-parent-node`.
Почему классы без приставки ue?

2017-07-11 14:02 UTC, AlekseySorokin commented
В рамках ПР поменяй стиль курсора при отключении сортировки. Когда наводишь на заголовок столбца, по которому нельзя сортировать, курсор всё равно меняется (как будто сортировка поддерживается.

2017-07-21 13:55 UTC, niksamokhvalov approved these changes

2017-07-21 13:55 UTC, merged