Paginations settings service
universal-editor/universal-editor pull request #197
Opened 2017-09-01 12:22 UTC by NobodyDies

Создан сервис хранящий настройки пагинатора и выставляющий эти настройки для компонентов с учетом переданных и дефолтных

2017-09-04 14:16 UTC, niksamokhvalov approved these changes

2017-09-04 14:17 UTC, AlekseySorokin reviewed
Код в некоторых местах сильно едет.
И много где нет ';' в конце команд. (http://take.ms/UNhUL)
(наверное дело в ide). 
Просьба поправить.

2017-09-05 09:25 UTC, NobodyDies commented
Исправил отступы. Привел все к стандарту проекта.

2017-09-05 09:33 UTC, AlekseySorokin approved these changes

2017-09-05 14:52 UTC, niksamokhvalov requested changes

2017-09-05 14:52 UTC, niksamokhvalov commented on docs/ru/events.md
> ++ `$id` – id компонента, которое инициирует отправку запроса на чтение данных;
Кстати, надо задокументировать настройку `$id` у компонентов. Сейчас в документации нет никакой информации об этом.

2017-09-05 15:37 UTC, AlekseySorokin commented on docs/ru/events.md
> ++ `$id` – id компонента, которое инициирует отправку запроса на чтение данных;
Добавил небольшое описание
https://github.com/universal-editor/universal-editor/pull/197/files#diff-a3463342907245c6e1225e989fe59d4fR65

2017-09-05 16:12 UTC, niksamokhvalov approved these changes

2017-09-05 16:12 UTC, merged