Changed building.
universal-editor/universal-editor pull request #222
Opened 2017-12-11 16:13 UTC by AlekseySorokin

В каталог dist добавлена сборка неминифицированной версии с source map.

2017-12-12 12:14 UTC, NobodyDies requested changes
Нашел странный пакет в зависимостях, вроде он не нужен.

2017-12-12 12:14 UTC, NobodyDies commented on package.json
> +    "merge": "^1.2.0",
может я чего то не вижу, но вроде как либо не используется в сборщике

2017-12-12 13:20 UTC, AlekseySorokin commented on package.json
> +    "merge": "^1.2.0",
ты прав. я изначально его юзал, но в итоге он мне не понадобился. Нужно убрать.

2017-12-12 13:22 UTC, AlekseySorokin commented on package.json
> +    "merge": "^1.2.0",
done

2017-12-13 10:43 UTC, NobodyDies approved these changes

2017-12-14 14:15 UTC, merged