Fix documentation.
universal-editor/universal-editor pull request #223
Opened 2017-12-15 15:48 UTC by AlekseySorokin

Поправлена документация для события ue:componentValueChanged.

2017-12-18 15:44 UTC, NobodyDies approved these changes

2017-12-21 12:32 UTC, niksamokhvalov requested changes

2017-12-21 12:32 UTC, niksamokhvalov commented on docs/ru/events.md
> +Событие вызывается при изменениях в модели данных в `ue-form` компоненте, но слушается всеми компонентами включенные в компонент формы. Он предназначено для обновления таких динамичных свойств как us
> Он предназначено

Опечатка.

2017-12-26 08:27 UTC, AlekseySorokin commented on docs/ru/events.md
> +Событие вызывается при изменениях в модели данных в `ue-form` компоненте, но слушается всеми компонентами включенные в компонент формы. Он предназначено для обновления таких динамичных свойств как us
Опечатку поправил

2017-12-26 08:46 UTC, niksamokhvalov approved these changes

2017-12-26 08:46 UTC, merged