unification component date
universal-editor/universal-editor pull request #80
Opened 2016-12-27 04:41 UTC by muravev

2016-12-27 10:02 UTC, AlekseySorokin approved these changes
Все в норме.

2016-12-27 12:00 UTC, niksamokhvalov commented
Компонент должен учитывать выбранный язык в конфигурации редактора.

2016-12-27 12:00 UTC, niksamokhvalov requested changes
Компонент должен учитывать выбранный язык в конфигурации редактора.

2017-01-10 08:38 UTC, niksamokhvalov approved these changes

2017-01-10 08:39 UTC, merged