changelog
universal-editor/universal-editor pull request #82
Opened 2016-12-27 12:21 UTC by muravev

2016-12-27 12:25 UTC, niksamokhvalov requested changes

2016-12-27 12:25 UTC, niksamokhvalov commented on CHANGELOG.md
> +## Update
Нарушена структура (уровень вложенности, см. http://keepachangelog.com/ru/0.3.0/).

2016-12-27 12:26 UTC, niksamokhvalov requested changes

2016-12-27 12:26 UTC, niksamokhvalov commented on CHANGELOG.md
> +* Added validators for fields components.
Почему это в разделе Update?

2017-01-30 08:05 UTC, niksamokhvalov approved these changes

2017-02-28 10:16 UTC, AlekseySorokin approved these changes

2017-02-28 10:19 UTC, merged