Go to webpack
universal-editor/universal-editor pull request #89
Opened 2017-01-12 09:19 UTC by AlekseySorokin

Configured webpack.
Bilding bundle.min.js and core.min.js.

2017-01-12 16:17 UTC, niksamokhvalov requested changes

2017-01-12 16:17 UTC, niksamokhvalov commented on README.md
> +Running console with Administrator permissions.
Чем обосновано такое требование?

2017-01-12 16:17 UTC, niksamokhvalov commented on README.md
> +* `webpack-dev-server`: watch sources and build, create web server.*
Что бы можно было гибко менять вызовы, давай команды назовём вот так:

`npm run dev` — поднимается сервер, приложение собирается в каталог app/.
`npm run build` — сборка дистрибутива в dist/.
`npm run dist` — поднимает сервер, смотрящий на каталог dist/.

Это описывается в package.json, например:
```
"scripts": {
  "dev": "NODE_ENV=development webpack-dev-server --progress",
  "build": "NODE_ENV=production webpack --progress"
}
```

2017-01-12 16:17 UTC, niksamokhvalov commented on bower.json
> +    "./dist/core.min.js"
А bundle.min.js тут разве не должен быть?

2017-01-12 16:17 UTC, niksamokhvalov commented on src/config.js
> +var ue = new UniversalEditor.constructor('universal-editor', {
Это обязательно? Не хотелось бы отказываться от лаконичного `new UniversalEditor()`.

2017-01-12 16:17 UTC, niksamokhvalov commented on src/inject/inject.js
> +require("angular-moment/angular-moment.js");
Одинарные кавычки должны быть.

2017-01-12 16:17 UTC, niksamokhvalov commented on src/module/components/componentWrapper/componentWrapper.component.js
> +    //var $ = require('jquery');
Зачем тут закомментированная строка?

2017-01-12 16:17 UTC, niksamokhvalov commented on src/module/components/ueButtonGoto/ueButtonGoto.controller.js
> +         //   console.log("angular version(webpack) is " + angular.version.full);
По-моему это лишнее.

2017-01-12 16:17 UTC, niksamokhvalov commented on src/module/universal-editor.js
> +            var app = angular.module(moduleName, ['universal.editor', 'ui.bootstrap']).config(['$stateProvider', '$urlRouterProvider', '$injector', 'configDataProvider', function($stateProvider, $url
А разве модуль `ui.bootstrap` не должен быть уже включен в состав модуля `universal.editor`?

2017-01-12 16:17 UTC, niksamokhvalov commented on webpack.config.js
> +    var localHost = 'universal-editor.local', defaultlocalHost = '127.0.0.1';
Давай сделаем universal-editor.dev, во имя единообразия с сервером бекенда.

2017-01-13 08:44 UTC, AlekseySorokin commented on README.md
> +Running console with Administrator permissions.
Это рекомендация. Если запустить без прав администратора не сработает автоматическое занесение в host маршрута http://universal-editor.dev  откроется адрес http://localhost.

2017-01-13 08:45 UTC, AlekseySorokin commented on README.md
> +* `webpack-dev-server`: watch sources and build, create web server.*
Понял сделаю.

2017-01-13 08:49 UTC, AlekseySorokin commented on bower.json
> +    "./dist/core.min.js"
Часто при сборке пользуются bower-плагинами, которые цепляют файлы из bower.json (раздел main). Если там указать еще и bundle.min.js. То разработчику придется переопределять в своем bower.json раздел main, иначе плагин возьмет оба файла и заинжектит их на страницу.
Подумал, что правильнее здесь указать ссылку на файл без зависимостей.

2017-01-13 08:53 UTC, AlekseySorokin commented on src/config.js
> +var ue = new UniversalEditor.constructor('universal-editor', {
Хорошо. Есть такой вариант:

```
function UniversalEditor(id, config) {
  //логика
  return {
    module: // созданный модуль
    angular: // версия ангуляр внутри бандла
  };
}

```

2017-01-13 08:54 UTC, AlekseySorokin commented on src/inject/inject.js
> +require("angular-moment/angular-moment.js");
+

2017-01-13 08:55 UTC, AlekseySorokin commented on src/module/universal-editor.js
> +            var app = angular.module(moduleName, ['universal.editor', 'ui.bootstrap']).config(['$stateProvider', '$urlRouterProvider', '$injector', 'configDataProvider', function($stateProvider, $url
согласен. он не нужен здесь.

2017-01-13 10:50 UTC, AlekseySorokin commented on README.md
> +* `webpack-dev-server`: watch sources and build, create web server.*
Может вот так лучше?

```
"scripts": {
    "serve": "webpack-dev-server --display-modules",
    "serve:dist": "webpack-dev-server -p",
    "build": "webpack -p",
    "dev": "webpack --display-modules"
  }
```

2017-01-13 12:06 UTC, AlekseySorokin commented on README.md
> +* `webpack-dev-server`: watch sources and build, create web server.*
webpack-dev-server не будет собирать файлы в директорую. Он хранит их в памяти, а не на диск и обосновывает это скоростью доступа к ним. Если мы хотим посмотреть содержимое бандла, то в браузере можно будет набрать universal-editor.dev/bundle.js.
А чтобы сделать сборку в директорию, то будем пользоваться вот этими командами
```
"build": "webpack -p",
"dev": "webpack --display-modules"
```

2017-01-13 16:46 UTC, niksamokhvalov commented on README.md
> +Running console with Administrator permissions.
А, понятно. Пропиши тогда это пояснение, плиз.

2017-01-13 16:47 UTC, niksamokhvalov commented on bower.json
> +    "./dist/core.min.js"
Добро.

2017-01-13 16:50 UTC, niksamokhvalov commented on src/config.js
> +var ue = new UniversalEditor.constructor('universal-editor', {
Напомни, module как используется?

2017-01-16 06:36 UTC, AlekseySorokin commented on src/config.js
> +var ue = new UniversalEditor.constructor('universal-editor', {
В данном случае module это angular.module('unEditor-' + id). В общем, это модуль, который создается ангуляром в конструкторе.

2017-01-17 16:48 UTC, niksamokhvalov requested changes

2017-01-17 16:48 UTC, niksamokhvalov commented on webpack.config.js
> +   //  console.log(RUNNING_SERVER);
Опять?

2017-01-18 09:15 UTC, niksamokhvalov approved these changes

2017-01-18 10:12 UTC, merged