Mod templates
universal-editor/universal-editor pull request #90
Opened 2017-01-16 13:01 UTC by muravev

Added property modTemplate and disabled for components.

2017-01-16 15:52 UTC, niksamokhvalov requested changes
Нельзя засовывать две фичи в один ПР. Больше так не делай, пожалуйста.

2017-01-16 15:52 UTC, niksamokhvalov commented on src/module/components/ueCheckbox/ueCheckbox.controller.js
> +        vm.field_id = "id";
1. Зачем тут двойные кавычки?
1. Почему в других местах переменные названы в camelCase, а тут в snake_case?
1. Ты так задаёшь значения по-умолчанию? Названия полей ведь через конфигурацию редактора должны задаваться.

2017-01-16 15:52 UTC, niksamokhvalov commented on src/module/components/universalEditor/universalEditor.scss
> +.disabled_field {
Почему в других местах названия написаны в lisp-стиле, а здесь в snake_case?

2017-01-16 15:52 UTC, niksamokhvalov commented on src/module/controllers/Base.controller.js
> +        if(componentSettings && componentSettings.modeTemplate){
Оформлено не по код-стайлу.

2017-01-17 10:34 UTC, muravev commented on src/module/components/ueCheckbox/ueCheckbox.controller.js
> +        vm.field_id = "id";
3. Да все верное, задается в конфиге. Но если values, а не  valuesRemote, то эти параметры не задаются, но для работы checkbox, dropdown, autocomplete они нужны, поэтому задаются по умолчанию.

2017-01-17 16:49 UTC, niksamokhvalov commented on src/module/components/ueCheckbox/ueCheckbox.controller.js
> +        vm.field_id = "id";
Понятно.

2017-01-17 16:52 UTC, niksamokhvalov approved these changes

2017-01-18 09:45 UTC, AlekseySorokin approved these changes
Принято.

2017-01-18 11:04 UTC, merged