Delete routing
universal-editor/universal-editor pull request #95
Opened 2017-01-23 15:24 UTC by muravev

2017-01-23 15:57 UTC, niksamokhvalov requested changes
Хорошо получилось, но надо причесать.

2017-01-23 15:57 UTC, niksamokhvalov commented on src/module/components/ueButtonLink/ueButtonLink.controller.js
> +                    console.warn('Стейт ' + state + ' не найден в конфигурационном файле.');
На русском языке ничего, кроме русской документации, не пишем.

2017-01-23 15:57 UTC, niksamokhvalov commented on src/module/components/ueForm/ueForm.controller.js
> +            pkKey = 'pk';// + EditEntityStorage.getLevelChild($state.current.name);
Зачем нужен закомментированный код?

2017-01-23 15:57 UTC, niksamokhvalov commented on src/testApp/components.controller.js
> +                                                    //настройки компонента
На русском ничего, кроме русской документации, не пишем. Да и комментарий этот тут лишний.

2017-01-23 15:57 UTC, niksamokhvalov commented on src/testApp/index.js
> +                template: '<universal-editor data-ue-Config="vm.config"></universal-editor>',
> data-ue-Config

Может `ue-config`?

2017-01-23 15:57 UTC, niksamokhvalov commented on src/testApp/index.js
> +                template: '<universal-editor data-ue-Config="vm.config"></universal-editor>',
> vm.config

Думаю, что это не самое удачное название. Переменных с конфигами может быть сколько угодно, поэтому я бы сделал акцент на то, что это конфиг редактора: `vm.ueConfig`.

2017-01-26 13:53 UTC, AlekseySorokin approved these changes
Принято.

2017-01-26 15:57 UTC, niksamokhvalov requested changes
Порядок. Давай немного красоты наведём, и можно мержить.

2017-01-26 15:57 UTC, niksamokhvalov commented on dist/index.js
> +    angular.module('testApp', ['ui.router', 'universal.editor']);
Переименуй в demoApp. И далее по тексту, test заменить на demo. Эта приложуха будет демкой.

2017-01-26 15:57 UTC, niksamokhvalov commented on src/module/components/universalEditor/universalEditor.controller.js
> +        function getHash() {
Что это такое? Не забывайте писать комментарии к функциям.

2017-01-27 07:58 UTC, niksamokhvalov approved these changes

2017-01-27 07:59 UTC, merged